version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: ShareIt-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: ShareIt-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_POSTGRES_USER=shareit
      - SPRING_POSTGRES_PASSWORD=2244

  db:
    image: postgres:14.6-alpine
    container_name: ShareIt-DataBase
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=2244